In [65]:
#1. Importing the dataset

In [66]:
#imports
import os
import pandas as pd
import numpy as np
import random
random.seed(1)

In [67]:
#!pip install xport


In [68]:
# Converting the .XPT to .CSV
#!python -m xport LLCP2021.xpt > LLCP2022.csv

In [69]:
#read in the dataset (select 2021)
brfss_2021_dataset = pd.read_csv("../Anaconda_Titans/LLCP2021.csv")

In [70]:
#How many rows and columns
brfss_2021_dataset.shape

(438693, 303)

In [71]:
#check that the data loaded in is in the correct format
pd.set_option('display.max_columns', 500)
brfss_2021_dataset.head()

_STATE  FMONTH    IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
0     1.0     1.0  1192021       1    19   2021    1100.0  2021000001   
1     1.0     1.0  1212021       1    21   2021    1100.0  2021000002   
2     1.0     1.0  1212021       1    21   2021    1100.0  2021000003   
3     1.0     1.0  1172021       1    17   2021    1100.0  2021000004   
4     1.0     1.0  1152021       1    15   2021    1100.0  2021000005   

           _PSU  CTELENM1  PVTRESD1  COLGHOUS  STATERE1  CELPHON1  LADULT1  \
0  2.021000e+09       1.0       1.0       NaN       1.0       2.0      1.0   
1  2.021000e+09       1.0       1.0       NaN       1.0       2.0      1.0   
2  2.021000e+09       1.0       1.0       NaN       1.0       2.0      1.0   
3  2.021000e+09       1.0       1.0       NaN       1.0       2.0      1.0   
4  2.021000e+09       1.0       1.0       NaN       1.0       2.0      1.0   

   COLGSEX  NUMADULT  LANDSEX  NUMMEN  NUMWOMEN  RESPSLCT  SAFETIME  CTELNUM1  \
0      NaN       2.0      NaN     1.0       1.0       2.0       NaN       NaN   
1      NaN       2.0      NaN     1.0       1.0       2.0       NaN       NaN   
2      NaN       2.0      NaN     1.0       1.0       2.0       NaN       NaN   
3      NaN       2.0      NaN     1.0       1.0       2.0       NaN       NaN   
4      NaN       2.0      NaN     1.0       1.0       1.0       NaN       NaN   

   CELLFON5  CADULT1  CELLSEX  PVTRESD3  CCLGHOUS  CSTATE1  LANDLINE  HHADULT  \
0       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
1       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
2       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
3       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   
4       NaN      NaN      NaN       NaN       NaN      NaN       NaN      NaN   

   SEXVAR  GENHLTH  PHYSHLTH  MENTHLTH  POORHLTH  PRIMINSR  PERSDOC3  \
0     2.0      5.0      20.0      10.0      88.0       3.0       1.0   
1     2.0      3.0      88.0      88.0       NaN       1.0       2.0   
2     2.0      2.0      88.0      88.0       NaN       2.0       2.0   
3     2.0      2.0      88.0      10.0      88.0       2.0       1.0   
4     1.0      5.0      30.0      88.0      30.0       3.0       1.0   

   MEDCOST1  CHECKUP1  EXERANY2  BPHIGH6  BPMEDS  CHOLCHK3  TOLDHI3  CHOLMED3  \
0       2.0       2.0       2.0      3.0     NaN       2.0      1.0       1.0   
1       2.0       1.0       1.0      1.0     1.0       2.0      1.0       1.0   
2       2.0       1.0       2.0      1.0     1.0       2.0      2.0       2.0   
3       2.0       1.0       1.0      1.0     1.0       2.0      1.0       2.0   
4       2.0       1.0       1.0      4.0     NaN       2.0      1.0       1.0   

   CVDINFR4  CVDCRHD4  CVDSTRK3  ASTHMA3  ASTHNOW  CHCSCNCR  CHCOCNCR  \
0       2.0       2.0       2.0      1.0      1.0       2.0       2.0   
1       2.0       1.0       2.0      2.0      NaN       2.0       2.0   
2       2.0       1.0       2.0      2.0      NaN       2.0       2.0   
3       2.0       2.0       2.0      2.0      NaN       2.0       2.0   
4       1.0       7.0       1.0      2.0      NaN       2.0       2.0   

   CHCCOPD3  ADDEPEV3  CHCKDNY2  DIABETE4  DIABAGE3  HAVARTH5  ARTHEXER  \
0       1.0       2.0       2.0       3.0       NaN       1.0       2.0   
1       2.0       2.0       1.0       1.0      98.0       1.0       1.0   
2       2.0       2.0       2.0       1.0      98.0       2.0       NaN   
3       2.0       2.0       2.0       1.0      56.0       2.0       NaN   
4       2.0       2.0       2.0       1.0      65.0       2.0       NaN   

   ARTHEDU  LMTJOIN3  ARTHDIS2  JOINPAI2  MARITAL  EDUCA  RENTHOM1  NUMHHOL3  \
0      2.0       2.0       1.0       8.0      1.0    4.0       1.0       1.0   
1      2.0       1.0       1.0      10.0      9.0    6.0       1.0       2.0   
2      NaN       NaN       NaN       NaN      3.0    4.0       1.0     

In [72]:
c= brfss_2021_dataset[brfss_2021_dataset.DIABETE4 == 4]
c

_STATE  FMONTH    IDATE  IMONTH  IDAY  IYEAR  DISPCODE       SEQNO  \
38         1.0     3.0  3112021       3    11   2021    1100.0  2021000039   
43         1.0     3.0  3172021       3    17   2021    1100.0  2021000044   
46         1.0     3.0  3172021       3    17   2021    1100.0  2021000047   
69         1.0     2.0  2222021       2    22   2021    1100.0  2021000070   
75         1.0     3.0  3292021       3    29   2021    1100.0  2021000076   
...        ...     ...      ...     ...   ...    ...       ...         ...   
438549    78.0    12.0  1262022       1    26   2022    1100.0  2021001242   
438550    78.0    12.0  1202022       1    20   2022    1100.0  2021001243   
438601    78.0    12.0  1052022       1     5   2022    1100.0  2021001294   
438633    78.0    12.0  1212022       1    21   2022    1100.0  2021001326   
438653    78.0    12.0  1192022       1    19   2022    1100.0  2021001346   

                _PSU  CTELENM1  PVTRESD1  COLGHOUS  STATERE1  CELPHON1  \
38      2.021000e+09       1.0       1.0       NaN       1.0       2.0   
43      2.021000e+09       1.0       1.0       NaN       1.0       2.0   
46      2.021000e+09       1.0       1.0       NaN       1.0       2.0   
69      2.021000e+09       1.0       1.0       NaN       1.0       2.0   
75      2.021000e+09       1.0       1.0       NaN       1.0       2.0   
...              ...       ...       ...       ...       ...       ...   
438549  2.021001e+09       NaN       NaN       NaN       NaN       NaN   
438550  2.021001e+09       NaN       NaN       NaN       NaN       NaN   
438601  2.021001e+09       NaN       NaN       NaN       NaN       NaN   
438633  2.021001e+09       NaN       NaN       NaN       NaN       NaN   
438653  2.021001e+09       NaN       NaN       NaN       NaN       NaN   

        LADULT1  COLGSEX  NUMADULT  LANDSEX  NUMMEN  NUMWOMEN  RESPSLCT  \
38          1.0      NaN       1.0      2.0     NaN       NaN       NaN   
43          1.0      NaN       1.0      2.0     NaN       NaN       NaN   
46          1.0      NaN       2.0      NaN     2.0       0.0       NaN   
69          1.0      NaN       1.0      2.0     NaN       NaN       NaN   
75          1.0      NaN       1.0      1.0     NaN       NaN       NaN   
...         ...      ...       ...      ...     ...       ...       ...   
438549      NaN      NaN       NaN      NaN     NaN       NaN       NaN   
438550      NaN      NaN       NaN      NaN     NaN       NaN       NaN   
438601      NaN      NaN       NaN      NaN     NaN       NaN       NaN   
438633      NaN      NaN       NaN      NaN     NaN       NaN       NaN   
438653      NaN      NaN       NaN      NaN     NaN       NaN       NaN   

        SAFETIME  CTELNUM1  CELLFON5  CADULT1  CELLSEX  PVTRESD3  CCLGHOUS  \
38           NaN       NaN       NaN      NaN      NaN       NaN       NaN   
43           NaN       NaN       NaN      NaN      NaN       NaN       NaN   
46           NaN       NaN       NaN      NaN      NaN       NaN       NaN   
69           NaN       NaN       NaN      NaN      NaN       NaN       NaN   
75           NaN       NaN       NaN      NaN      NaN       NaN       NaN   
...          ...       ...       ...      ...      ...       ...       ...   
438549       1.0       1.0       1.0      1.0      2.0       1.0       NaN   
438550       1.0       1.0       1.0      1.0      2.0       1.0       NaN   
438601       1.0       1.0       1.0      1.0      2.0       1.0       NaN   
438633       1.0       1.0       1.0      1.0      2.0       1.0       NaN   
438653       1.0       1.0       1.0      1.0      2.0       1.0       NaN   

        CSTATE1  LANDLINE  HHADULT  SEXVAR  GENHLTH  PHYSHLTH  MENTHLTH  \
38          NaN       NaN      NaN     2.0      4.0      88.0      88.0   
43          NaN       NaN      NaN     2.0      2.0      88.0      88.0   
46          NaN       NaN      NaN     1.0      3.0      88.0      88.0   
69          NaN       NaN      NaN     2.0  

In [73]:
## The dataset is showing 438,693 records and 303 columns. All records are showing the individual respons of individuals surveyed

In [74]:
# select specific columns
brfss_df_selected = brfss_2021_dataset[['_STATE','DIABETE4', '_RFHYPE6', '_RACE','ASTHMA3','TOLDHI3', 'CHOLCHK3', '_BMI5', 'SMOKE100', 'CVDSTRK3', '_MICHD', '_TOTINDA', '_FRTLT1A', '_VEGLT1A', 
                                         '_RFDRHV7', '_HLTHPLN', 'MEDCOST1', 'GENHLTH', 'MENTHLTH', 'PHYSHLTH', 'DIFFWALK', '_SEX', '_AGEG5YR', 'EDUCA', 'INCOME3' ]]

In [75]:
brfss_df_selected.shape

(438693, 25)

In [76]:
brfss_df_selected.head()

_STATE  DIABETE4  _RFHYPE6  _RACE  ASTHMA3  TOLDHI3  CHOLCHK3   _BMI5  \
0     1.0       3.0       1.0    1.0      1.0      1.0       2.0  1454.0   
1     1.0       1.0       2.0    2.0      2.0      1.0       2.0     NaN   
2     1.0       1.0       2.0    2.0      2.0      2.0       2.0  2829.0   
3     1.0       1.0       2.0    1.0      2.0      1.0       2.0  3347.0   
4     1.0       1.0       1.0    7.0      2.0      1.0       2.0  2873.0   

   SMOKE100  CVDSTRK3  _MICHD  _TOTINDA  _FRTLT1A  _VEGLT1A  _RFDRHV7  \
0       1.0       2.0     2.0       2.0       1.0       1.0       1.0   
1       2.0       2.0     1.0       1.0       1.0       1.0       1.0   
2       2.0       2.0     1.0       2.0       1.0       2.0       1.0   
3       2.0       2.0     2.0       1.0       1.0       1.0       1.0   
4       2.0       1.0     1.0       1.0       1.0       1.0       1.0   

   _HLTHPLN  MEDCOST1  GENHLTH  MENTHLTH  PHYSHLTH  DIFFWALK  _SEX  _AGEG5YR  \
0       1.0       2.0      5.0      10.0      20.0       2.0   2.0      11.0   
1       1.0       2.0      3.0      88.0      88.0       1.0   2.0      10.0   
2       1.0       2.0      2.0      88.0      88.0       2.0   2.0      11.0   
3       1.0       2.0      2.0      10.0      88.0       2.0   2.0       9.0   
4       1.0       2.0      5.0      88.0      30.0       1.0   1.0      12.0   

   EDUCA  INCOME3  
0    4.0      5.0  
1    6.0     77.0  
2    4.0      3.0  
3    4.0      7.0  
4    3.0      4.0

In [77]:
ab = brfss_df_selected[brfss_df_selected.DIABETE4 == 4]
ab

_STATE  DIABETE4  _RFHYPE6  _RACE  ASTHMA3  TOLDHI3  CHOLCHK3   _BMI5  \
38         1.0       4.0       2.0    2.0      2.0      1.0       2.0  3292.0   
43         1.0       4.0       2.0    1.0      2.0      1.0       2.0  3277.0   
46         1.0       4.0       1.0    1.0      2.0      2.0       3.0  2837.0   
69         1.0       4.0       1.0    2.0      2.0      1.0       2.0  2988.0   
75         1.0       4.0       2.0    1.0      2.0      2.0       3.0  2798.0   
...        ...       ...       ...    ...      ...      ...       ...     ...   
438549    78.0       4.0       2.0    2.0      2.0      1.0       2.0  2385.0   
438550    78.0       4.0       2.0    2.0      2.0      1.0       2.0  3495.0   
438601    78.0       4.0       1.0    2.0      2.0      1.0       2.0     NaN   
438633    78.0       4.0       2.0    9.0      2.0      2.0       2.0  3004.0   
438653    78.0       4.0       1.0    2.0      1.0      2.0       3.0  4056.0   

        SMOKE100  CVDSTRK3  _MICHD  _TOTINDA  _FRTLT1A  _VEGLT1A  _RFDRHV7  \
38           2.0       2.0     2.0       2.0       1.0       1.0       1.0   
43           2.0       2.0     2.0       2.0       1.0       1.0       1.0   
46           2.0       2.0     2.0       1.0       1.0       1.0       1.0   
69           2.0       2.0     2.0       1.0       1.0       2.0       1.0   
75           1.0       2.0     2.0       2.0       2.0       2.0       1.0   
...          ...       ...     ...       ...       ...       ...       ...   
438549       2.0       2.0     2.0       1.0       1.0       1.0       1.0   
438550       2.0       2.0     2.0       2.0       2.0       1.0       1.0   
438601       2.0       2.0     1.0       1.0       9.0       1.0       1.0   
438633       2.0       2.0     2.0       1.0       1.0       1.0       1.0   
438653       2.0       2.0     2.0       1.0       2.0       2.0       1.0   

        _HLTHPLN  MEDCOST1  GENHLTH  MENTHLTH  PHYSHLTH  DIFFWALK  _SEX  \
38           1.0       2.0      4.0      88.0      88.0       2.0   2.0   
43           1.0       2.0      2.0      88.0      88.0       2.0   2.0   
46           1.0       2.0      3.0      88.0      88.0       2.0   1.0   
69           1.0       2.0      5.0       3.0      13.0       1.0   2.0   
75           1.0       2.0      2.0      88.0      88.0       2.0   1.0   
...          ...       ...      ...       ...       ...       ...   ...   
438549       1.0       2.0      3.0      10.0       5.0       2.0   2.0   
438550       1.0       2.0      2.0      88.0      30.0       1.0   2.0   
438601       1.0       2.0      3.0      77.0      88.0       1.0   2.0   
438633       1.0       2.0      3.0      88.0      77.0       1.0   2.0   
438653       1.0       2.0      4.0       7.0      88.0       2.0   2.0   

        _AGEG5YR  EDUCA  INCOME3  
38          11.0    4.0     99.0  
43          11.0    5.0      5.0  
46           9.0    6.0     99.0  
69          10.0    5.0      3.0  
75          10.0    6.0     99.0  
...          ...    ...      ...  
438549       8.0    6.0      7.0  
438550       9.0    5.0      6.0  
438601       5.0    6.0      7.0  
438633       9.0    6.0      6.0  
438653       2.0    4.0      6.0  

[9942 rows x 25 columns]

In [78]:
#2. Cleaning the data

In [79]:
#2.1 Drop missing values
#Drop Missing Values - eliminates 108,338 rows out right away
brfss_df_selected = brfss_df_selected.dropna()
brfss_df_selected.shape

(330355, 25)

In [80]:
#2.2 Transforming the values for the Machine Learning algorithms
    #In order to do this part, I referenced the codebook which says what each column/feature/question is:
    https://www.cdc.gov/brfss/annual_data/2021/pdf/codebook21_llcp-v2-508.pdf

IndentationError: unexpected indent (557419174.py, line 3)

In [81]:
# DIABETE4
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for pre-diabetes or borderline diabetes, 2 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['DIABETE4'] = brfss_df_selected['DIABETE4'].replace({2:0, 3:0, 1:2, 4:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIABETE4 != 9]
brfss_df_selected.DIABETE4.unique()

array([0., 2., 1.])

In [82]:
#1 _RFHYPE6
#Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
brfss_df_selected['_RFHYPE6'] = brfss_df_selected['_RFHYPE6'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFHYPE6 != 9]
brfss_df_selected._RFHYPE6.unique()

array([0., 1.])

In [93]:
# ASTHMA
# going to make this ordinal. 0 is for no diabetes or only during pregnancy, 1 is for pre-diabetes or borderline diabetes, 2 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['ASTHMA3'] = brfss_df_selected['ASTHMA3'].replace({2:0, 3:0, 1:2, 4:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected.ASTHMA3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.ASTHMA3 != 9]
brfss_df_selected.ASTHMA3.unique()

array([2., 0.])

In [83]:
#2 TOLDHI3
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['TOLDHI3'] = brfss_df_selected['TOLDHI3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.TOLDHI3 != 9]
brfss_df_selected.TOLDHI3.unique()

array([1., 0.])

In [88]:
#3 CHOLCHK3
# Change 3 to 0 and 2 to 0 for Not checked cholesterol in past 5 years
# Remove 9
brfss_df_selected['CHOLCHK3'] = brfss_df_selected['CHOLCHK3'].replace({3:0,2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CHOLCHK3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.CHOLCHK3 != 9]
brfss_df_selected.CHOLCHK3.unique()

array([0., 8., 5., 4., 6.])

In [91]:
#4 _BMI5 (no changes, just note that these are BMI * 100. So for example a BMI of 1850 is really 18.50)
brfss_df_selected['_BMI5'] = brfss_df_selected['_BMI5'].div(100).round(0)
brfss_df_selected._BMI5.unique()

array([0.])

In [92]:
#5 SMOKE100
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['SMOKE100'] = brfss_df_selected['SMOKE100'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.SMOKE100 != 9]
brfss_df_selected.SMOKE100.unique()

array([1., 0.])

In [94]:
#6 CVDSTRK3
# Change 2 to 0 because it is No
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_selected['CVDSTRK3'] = brfss_df_selected['CVDSTRK3'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.CVDSTRK3 != 9]
brfss_df_selected.CVDSTRK3.unique()

array([0., 1.])

In [95]:
#7 _MICHD
#Change 2 to 0 because this means did not have MI or CHD
brfss_df_selected['_MICHD'] = brfss_df_selected['_MICHD'].replace({2: 0})
brfss_df_selected._MICHD.unique()

array([0., 1.])

In [96]:
#8 _TOTINDA
# 1 for physical activity
# change 2 to 0 for no physical activity
# Remove all 9 (don't know/refused)
brfss_df_selected['_TOTINDA'] = brfss_df_selected['_TOTINDA'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._TOTINDA != 9]
brfss_df_selected._TOTINDA.unique()

array([0., 1.])

In [97]:
#9 _FRTLT1A
# Change 2 to 0. this means no fruit consumed per day. 1 will mean consumed 1 or more pieces of fruit per day 
# remove all dont knows and missing 9
brfss_df_selected['_FRTLT1A'] = brfss_df_selected['_FRTLT1A'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._FRTLT1A != 9]
brfss_df_selected._FRTLT1A.unique()

array([1., 0.])

In [98]:
#10 _VEGLT1A
# Change 2 to 0. this means no vegetables consumed per day. 1 will mean consumed 1 or more pieces of vegetable per day 
# remove all dont knows and missing 9
brfss_df_selected['_VEGLT1A'] = brfss_df_selected['_VEGLT1A'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._VEGLT1A != 9]
brfss_df_selected._VEGLT1A.unique()

array([1., 0.])

In [99]:
#11 _RFDRHV7
# Change 1 to 0 (1 was no for heavy drinking). change all 2 to 1 (2 was yes for heavy drinking)
# remove all dont knows and missing 9
brfss_df_selected['_RFDRHV7'] = brfss_df_selected['_RFDRHV7'].replace({1:0, 2:1})
brfss_df_selected = brfss_df_selected[brfss_df_selected._RFDRHV7 != 9]
brfss_df_selected._RFDRHV7.unique()

array([0., 1.])

In [100]:
#12 _HLTHPLN
# 1 is yes, change 2 to 0 because it is No health care access
# remove 7 and 9 for don't know or refused
brfss_df_selected['_HLTHPLN'] = brfss_df_selected['_HLTHPLN'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPLN != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected._HLTHPLN != 9]
brfss_df_selected._HLTHPLN.unique()

array([1., 0.])

In [101]:
#13 MEDCOST1
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don/t know and 9 for refused
brfss_df_selected['MEDCOST1'] = brfss_df_selected['MEDCOST1'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MEDCOST1 != 9]
brfss_df_selected.MEDCOST1.unique()

array([0., 1.])

In [102]:
#14 GENHLTH
# This is an ordinal variable that I want to keep (1 is Excellent -> 5 is Poor)
# Remove 7 and 9 for don't know and refused
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.GENHLTH != 9]
brfss_df_selected.GENHLTH.unique()

array([5., 2., 3., 4., 1.])

In [103]:
#15 MENTHLTH
# already in days so keep that, scale will be 0-30
# change 88 to 0 because it means none (no bad mental health days)
# remove 77 and 99 for don't know not sure and refused
brfss_df_selected['MENTHLTH'] = brfss_df_selected['MENTHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.MENTHLTH != 99]
brfss_df_selected.MENTHLTH.unique()

array([10.,  0.,  5., 25.,  2.,  7., 30.,  3., 14., 20.,  8.,  1., 15.,
        4., 28., 24., 21., 12.,  6., 22., 27., 18., 13., 17., 16.,  9.,
       19., 29., 23., 11., 26.])

In [104]:
#16 PHYSHLTH
# already in days so keep that, scale will be 0-30
# change 88 to 0 because it means none (no bad mental health days)
# remove 77 and 99 for don't know not sure and refused
brfss_df_selected['PHYSHLTH'] = brfss_df_selected['PHYSHLTH'].replace({88:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.PHYSHLTH != 99]
brfss_df_selected.PHYSHLTH.unique()

array([20.,  0., 30., 25.,  1.,  4., 10.,  2.,  3., 15.,  8., 13., 14.,
        5.,  7.,  6., 24., 29., 18.,  9., 16., 17., 26., 28., 12., 21.,
       27., 11., 19., 22., 23.])

In [105]:
#17 DIFFWALK
# change 2 to 0 for no. 1 is already yes
# remove 7 and 9 for don't know not sure and refused
brfss_df_selected['DIFFWALK'] = brfss_df_selected['DIFFWALK'].replace({2:0})
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 7]
brfss_df_selected = brfss_df_selected[brfss_df_selected.DIFFWALK != 9]
brfss_df_selected.DIFFWALK.unique()

array([0., 1.])

In [106]:
#18 _SEX
# in other words - is respondent male (somewhat arbitrarily chose this change because men are at higher risk for heart disease)
# change 2 to 0 (female as 0). Male is 1
brfss_df_selected['_SEX'] = brfss_df_selected['_SEX'].replace({2:0})
brfss_df_selected._SEX.unique()

array([0., 1.])

In [107]:
#19 _AGEG5YR
# already ordinal. 1 is 18-24 all the way up to 13 wis 80 and older. 5 year increments.
# remove 14 because it is don't know or missing
brfss_df_selected = brfss_df_selected[brfss_df_selected._AGEG5YR != 14]
brfss_df_selected._AGEG5YR.unique()

array([11.,  9., 12., 13., 10.,  7.,  6.,  8.,  4.,  3.,  5.,  2.,  1.])

In [108]:
#20 EDUCA
# This is already an ordinal variable with 1 being never attended school or kindergarten only up to 6 being college 4 years or more
# Scale here is 1-6
# Remove 9 for refused:
brfss_df_selected = brfss_df_selected[brfss_df_selected.EDUCA != 9]
brfss_df_selected.EDUCA.unique()

array([4., 3., 5., 6., 2., 1.])

In [109]:
#21 INCOME3
# Variable is already ordinal with 1 being less than $10,000 all the way up to 8 being $75,000 or more
# Remove 77 and 99 for don't know and refused
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 77]
brfss_df_selected = brfss_df_selected[brfss_df_selected.INCOME3 != 99]
brfss_df_selected.INCOME3.unique()

array([ 5.,  3.,  7.,  4.,  6.,  8.,  2.,  9., 10.,  1., 11.])

In [110]:
#Check the shape of the dataset now: We have 235,879 cleaned rows and 25 columns (1 of which is our dependent variable)
brfss_df_selected.shape

(235879, 25)

In [111]:
#Let's see what the data looks like after Modifying Values
brfss_df_selected.head()

_STATE  DIABETE4  _RFHYPE6  _RACE  ASTHMA3  TOLDHI3  CHOLCHK3  _BMI5  \
0     1.0       0.0       0.0    1.0      2.0      1.0       0.0    0.0   
2     1.0       2.0       1.0    2.0      0.0      0.0       0.0    0.0   
3     1.0       2.0       1.0    1.0      0.0      1.0       0.0    0.0   
4     1.0       2.0       0.0    7.0      0.0      1.0       0.0    0.0   
5     1.0       0.0       0.0    1.0      0.0      0.0       0.0    0.0   

   SMOKE100  CVDSTRK3  _MICHD  _TOTINDA  _FRTLT1A  _VEGLT1A  _RFDRHV7  \
0       1.0       0.0     0.0       0.0       1.0       1.0       0.0   
2       0.0       0.0     1.0       0.0       1.0       0.0       0.0   
3       0.0       0.0     0.0       1.0       1.0       1.0       0.0   
4       0.0       1.0     1.0       1.0       1.0       1.0       0.0   
5       1.0       0.0     0.0       0.0       0.0       0.0       0.0   

   _HLTHPLN  MEDCOST1  GENHLTH  MENTHLTH  PHYSHLTH  DIFFWALK  _SEX  _AGEG5YR  \
0       1.0       0.0      5.0      10.0      20.0       0.0   0.0      11.0   
2       1.0       0.0      2.0       0.0       0.0       0.0   0.0      11.0   
3       1.0       0.0      2.0      10.0       0.0       0.0   0.0       9.0   
4       1.0       0.0      5.0       0.0      30.0       1.0   1.0      12.0   
5       1.0       0.0      3.0       0.0       0.0       1.0   1.0      13.0   

   EDUCA  INCOME3  
0    4.0      5.0  
2    4.0      3.0  
3    4.0      7.0  
4    3.0      4.0  
5    5.0      6.0

In [112]:
#Check Class Sizes of the heart disease column
brfss_df_selected.groupby(['DIABETE4']).size()

DIABETE4
0.0    196788
1.0      5607
2.0     33484
dtype: int64

In [119]:
#3. Make feature names more readable
#Rename the columns to make them more readable
brfss = brfss_df_selected.rename(columns = {'DIABETE4':'Diabetes', 
                                         '_RFHYPE6':'HighBP',
                                         '_RACE':'RACE',
                                         'ASTHMA3':'ASTHMA',  
                                         'TOLDHI3':'HighChol', 'CHOLCHK3':'CholCheck', 
                                         '_BMI5':'BMI', 
                                         'SMOKE100':'Smoker', 
                                         'CVDSTRK3':'Stroke', '_MICHD':'HeartDiseaseorAttack', 
                                         '_TOTINDA':'PhysActivity', 
                                         '_FRTLT1A':'Fruits', '_VEGLT1A':"Veggies", 
                                         '_RFDRHV7':'HvyAlcoholConsump', 
                                         '_HLTHPLN':'AnyHealthcare', 'MEDCOST1':'NoDocbcCost', 
                                         'GENHLTH':'GenHlth', 'MENTHLTH':'MentHlth', 'PHYSHLTH':'PhysHlth', 'DIFFWALK':'DiffWalk', 
                                         '_SEX':'Sex', '_AGEG5YR':'Age', 'EDUCA':'Education', 'INCOME3':'Income' })

In [120]:
brfss.head()

_STATE  Diabetes  HighBP  RACE  ASTHMA  HighChol  CholCheck  BMI  Smoker  \
0     1.0       0.0     0.0   1.0     2.0       1.0        0.0  0.0     1.0   
2     1.0       2.0     1.0   2.0     0.0       0.0        0.0  0.0     0.0   
3     1.0       2.0     1.0   1.0     0.0       1.0        0.0  0.0     0.0   
4     1.0       2.0     0.0   7.0     0.0       1.0        0.0  0.0     0.0   
5     1.0       0.0     0.0   1.0     0.0       0.0        0.0  0.0     1.0   

   Stroke  HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  \
0     0.0                   0.0           0.0     1.0      1.0   
2     0.0                   1.0           0.0     1.0      0.0   
3     0.0                   0.0           1.0     1.0      1.0   
4     1.0                   1.0           1.0     1.0      1.0   
5     0.0                   0.0           0.0     0.0      0.0   

   HvyAlcoholConsump  AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  \
0                0.0            1.0          0.0      5.0      10.0      20.0   
2                0.0            1.0          0.0      2.0       0.0       0.0   
3                0.0            1.0          0.0      2.0      10.0       0.0   
4                0.0            1.0          0.0      5.0       0.0      30.0   
5                0.0            1.0          0.0      3.0       0.0       0.0   

   DiffWalk  Sex   Age  Education  Income  
0       0.0  0.0  11.0        4.0     5.0  
2       0.0  0.0  11.0        4.0     3.0  
3       0.0  0.0   9.0        4.0     7.0  
4       1.0  1.0  12.0        3.0     4.0  
5       1.0  1.0  13.0        5.0     6.0

In [121]:
brfss.shape

(235879, 25)

In [122]:
#Check how many respondents have no diabetes, prediabetes or diabetes. Note the class imbalance!
brfss.groupby(['Diabetes']).size()

Diabetes
0.0    196788
1.0      5607
2.0     33484
dtype: int64

In [ ]:
#4. Save to CSV
#First save version where diabetes is the target variable and in the first column.
#This is the full cleaned dataset with prediabetes still there.

In [123]:
#************************************************************************************************
brfss.to_csv('diabetes_21_health_indicators_BRFSS2021.csv', sep=",", index=False)
#************************************************************************************************

In [ ]:
#5. Create Binary Dataset for diabetes vs. no diabetes
    #If we want to do binary classification of diabtes vs no diabetes that can be accomplished by either joining
    #the prediabetics with the diabetics, with the non-diabetics, or removing them entirely.
    #  I would like to add them to the diabetic group, as being told by a doctor you are prediabetic
    #  is an indication of diabetes risk and ultimately we are interested in risk.

In [ ]:
    #While we're at it, we can make the dataset balanced in a 50-50 split of non-diabetics to diabetics
    #and prediabetics. There are a sufficient number of records to do this randomly and yield predictive results.
    #There are 4631 (pre-diabetes) + 35346 (diabetes) so we can make a new 50-50 binary dataset of 39,977
    #diabetic risk individuals to 39,977 randomly selected non-diabetics.

In [ ]:
    #Note that because it is a survey it is always possible (actually likely) that some individuals will not have
    #been diagnosed yet but are either pre-diabetic or diabetic.

In [124]:
#Copy old table to new one.
brfss_binary = brfss
#Change the diabetics 2 to a 1 and pre-diabetics 1 to a 0, so that we have 0 meaning non-diabetic
# and pre-diabetic and 1 meaning diabetic.
brfss_binary['Diabetes'] = brfss_binary['Diabetes'].replace({1:0})
brfss_binary['Diabetes'] = brfss_binary['Diabetes'].replace({2:1})
#Change the column name to Diabetes_binary
brfss_binary = brfss_binary.rename(columns = {'Diabetes': 'Diabetes_binary'})
brfss_binary.Diabetes_binary.unique()

array([0., 1.])

In [125]:
#Show the change
brfss_binary.head()

_STATE  Diabetes_binary  HighBP  RACE  ASTHMA  HighChol  CholCheck  BMI  \
0     1.0              0.0     0.0   1.0     2.0       1.0        0.0  0.0   
2     1.0              1.0     1.0   2.0     0.0       0.0        0.0  0.0   
3     1.0              1.0     1.0   1.0     0.0       1.0        0.0  0.0   
4     1.0              1.0     0.0   7.0     0.0       1.0        0.0  0.0   
5     1.0              0.0     0.0   1.0     0.0       0.0        0.0  0.0   

   Smoker  Stroke  HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  \
0     1.0     0.0                   0.0           0.0     1.0      1.0   
2     0.0     0.0                   1.0           0.0     1.0      0.0   
3     0.0     0.0                   0.0           1.0     1.0      1.0   
4     0.0     1.0                   1.0           1.0     1.0      1.0   
5     1.0     0.0                   0.0           0.0     0.0      0.0   

   HvyAlcoholConsump  AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  \
0                0.0            1.0          0.0      5.0      10.0      20.0   
2                0.0            1.0          0.0      2.0       0.0       0.0   
3                0.0            1.0          0.0      2.0      10.0       0.0   
4                0.0            1.0          0.0      5.0       0.0      30.0   
5                0.0            1.0          0.0      3.0       0.0       0.0   

   DiffWalk  Sex   Age  Education  Income  
0       0.0  0.0  11.0        4.0     5.0  
2       0.0  0.0  11.0        4.0     3.0  
3       0.0  0.0   9.0        4.0     7.0  
4       1.0  1.0  12.0        3.0     4.0  
5       1.0  1.0  13.0        5.0     6.0

In [126]:
#show class sizes
brfss_binary.groupby(['Diabetes_binary']).size()

Diabetes_binary
0.0    202395
1.0     33484
dtype: int64

In [127]:
#Separate the 0(No Diabetes) and 1&2(Pre-diabetes and Diabetes)
#Get the 1s
is1 = brfss_binary['Diabetes_binary'] == 1
brfss_5050_1 = brfss_binary[is1]

#Get the 0s
is0 = brfss_binary['Diabetes_binary'] == 0
brfss_5050_0 = brfss_binary[is0] 

#Select the 39977 random cases from the 0 (non-diabetes group). we already have 35346 cases from the diabetes risk group
brfss_5050_0_rand1 = brfss_5050_0.take(np.random.permutation(len(brfss_5050_0))[:33484])

#Append the 39977 1s to the 39977 randomly selected 0s
brfss_5050 = brfss_5050_0_rand1.append(brfss_5050_1, ignore_index = True)

In [128]:
#Check that it worked. Now we have a dataset of 79,954 rows that is equally balanced with 50% 1 and 50% 0 for the target variable Diabetes_binary
brfss_5050.head()

_STATE  Diabetes_binary  HighBP  RACE  ASTHMA  HighChol  CholCheck  BMI  \
0    31.0              0.0     0.0   1.0     0.0       0.0        0.0  0.0   
1     9.0              0.0     1.0   1.0     0.0       1.0        0.0  0.0   
2    40.0              0.0     1.0   1.0     0.0       0.0        0.0  0.0   
3    29.0              0.0     0.0   1.0     0.0       0.0        0.0  0.0   
4    20.0              0.0     0.0   8.0     0.0       0.0        0.0  0.0   

   Smoker  Stroke  HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  \
0     0.0     0.0                   0.0           1.0     1.0      1.0   
1     0.0     0.0                   0.0           1.0     0.0      1.0   
2     1.0     0.0                   0.0           1.0     0.0      1.0   
3     0.0     0.0                   0.0           1.0     1.0      1.0   
4     0.0     0.0                   0.0           1.0     0.0      1.0   

   HvyAlcoholConsump  AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  \
0                0.0            1.0          0.0      1.0       0.0       0.0   
1                0.0            1.0          0.0      2.0       0.0       0.0   
2                0.0            1.0          0.0      3.0       0.0       0.0   
3                0.0            1.0          0.0      1.0       0.0       0.0   
4                0.0            1.0          0.0      2.0       0.0       0.0   

   DiffWalk  Sex   Age  Education  Income  
0       0.0  1.0   2.0        6.0     8.0  
1       0.0  1.0  10.0        4.0     8.0  
2       0.0  0.0   7.0        4.0     5.0  
3       0.0  0.0   8.0        4.0     9.0  
4       0.0  0.0   3.0        4.0     4.0

In [129]:
brfss_5050.tail()

_STATE  Diabetes_binary  HighBP  RACE  ASTHMA  HighChol  CholCheck  \
66963    78.0              1.0     1.0   2.0     0.0       0.0        0.0   
66964    78.0              1.0     1.0   2.0     0.0       1.0        0.0   
66965    78.0              1.0     1.0   2.0     2.0       1.0        0.0   
66966    78.0              1.0     1.0   2.0     0.0       1.0        0.0   
66967    78.0              1.0     1.0   8.0     0.0       1.0        4.0   

       BMI  Smoker  Stroke  HeartDiseaseorAttack  PhysActivity  Fruits  \
66963  0.0     0.0     0.0                   0.0           1.0     1.0   
66964  0.0     0.0     0.0                   0.0           0.0     1.0   
66965  0.0     0.0     0.0                   1.0           1.0     0.0   
66966  0.0     0.0     0.0                   0.0           0.0     0.0   
66967  0.0     0.0     0.0                   0.0           1.0     1.0   

       Veggies  HvyAlcoholConsump  AnyHealthcare  NoDocbcCost  GenHlth  \
66963      1.0                0.0            1.0          0.0      3.0   
66964      1.0                0.0            1.0          0.0      4.0   
66965      0.0                0.0            1.0          1.0      2.0   
66966      1.0                0.0            1.0          0.0      2.0   
66967      1.0                0.0            1.0          0.0      4.0   

       MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  Income  
66963       0.0       0.0       0.0  1.0  11.0        5.0     6.0  
66964       0.0       0.0       0.0  0.0  11.0        4.0     2.0  
66965      10.0       0.0       0.0  1.0   8.0        6.0     6.0  
66966       0.0       0.0       1.0  1.0  10.0        4.0     5.0  
66967       0.0       0.0       0.0  1.0  10.0        2.0     3.0

In [130]:
#See the classes are perfectly balanced now
brfss_5050.groupby(['Diabetes_binary']).size()

Diabetes_binary
0.0    33484
1.0    33484
dtype: int64

In [ ]:
#6. Save binary dataset and 50-50 binary balanced dataset to csv
These files have prediabetes added to the diabetes group. The 50-50 dataset takes it a step further
and has a randomly selected even split to help beginners train their models.

In [131]:
print(f'brfss_5050={brfss_5050.shape}',f'brfss_binary={brfss_binary.shape}')

brfss_5050=(66968, 25) brfss_binary=(235879, 25)


In [133]:
#Save the 50-50 balanced dataset to csv
#************************************************************************************************
brfss_5050.to_csv('diabetes_binary_5050split_health_indicators_BRFSS2021.csv', sep=",", index=False)
#************************************************************************************************

#Also save the original binary dataset to csv
#************************************************************************************************
brfss_binary.to_csv('diabetes_binary_health_indicators_BRFSS2021.csv', sep=",", index=False)
#************************************************************************************************